@startuml
left to right direction
database "DataBase"{
    Rectangle "Identities"{
        Rectangle Identity1{
        }
        Rectangle Identity2{
        }
        Rectangle ...{
       }
    }
}
Rectangle "Java Program" as JavaProgram {
    Rectangle Hibernate{
        [ORM] -- Identities : SQL Operations
    }
    [Identity]
    [DAO] -- ORM : Allows transparent mapping
    DAO -- Identity : Manages

}

Hibernate -- DataBase : JDBC Connection

@enduml