@startuml
left to right direction

Rectangle "Java Program" as java{
    Rectangle DAO {

    }
    Rectangle "Embedded Derby" as derby{

    }
}
DAO --> derby : jdbc
derby --> dbfiles

Rectangle "Java Program" as java2{
    Rectangle "DAO" as DAO2{
    }
    DAO2 -->derbys : jdbc
}
Rectangle "Derby Server" as derbys{

}
derbys --> dbfiles

Database "Database Files" as dbfiles{

}
@enduml