@startuml

left to right direction

Rectangle identitiy.xsd as idschema{

}
Rectangle identities.xml as idlist{
}

idlist --> idschema : validates against
idlist --> (JAVA - Parsing) : from text to <b>DOM</b>
(JAVA - Parsing) --> (JAVA - XPATH Computation) : <b>DOM</b> Document
(JAVA - XPATH Computation) --> (JAVA - XSLT Call) : Values are computed
(JAVA - XSLT Call) --> (JAVA - JSP) : <b>xml</b> to <b>html</b>
note right {
    a sub document is created and injected
    in the web page
}

Rectangle WebPage{
}
(JAVA - JSP) --> WebPage

user --> WebPage

@enduml