@startuml
rectangle Definition{
     (Identity)
}
(Identity) -- ("new" Operator)
note right
example:
Identity Thomas = new Identity("Thomas");
endnote
rectangle Instances{
	("new" Operator) --> (Quentin)
	("new" Operator)--> (Clément)
	("new" Operator) --> (Thomas)

}

@enduml