@startuml

(DocumentBuilderFactory)--(DocumentBuilder)
note right of (DocumentBuilder)
The document builder takes
the file as an argument for the parse
method
endnote
(DocumentBuilder) -- (Document) : Parses the file


@enduml
