@startuml

class Car {
	-String model
	-String brand
	+Car(String model, String brand)
	+String toString()
}
class MotorVehicle {
	-String engineType
	#boolean engineStarted
	+void start()
	+void stop()
}
MotorVehicle <|-- Car
@enduml