@startuml
legend
Subject Role-Organization Assignment
endlegend
(Identity) -- (Assignment)
(Assignment) -- (Role)
(Role) -- (Permission1)
(Role) -- (Permission2)
(Role) -- (Permission3)
rectangle Role {
 	(Role) .. (Organization)
}


@enduml