@startuml
left to right direction

Class Customer{
    name
    address
}

Class Account {
    balance
}

Class InvestmentAccount extends Account {

}

Class SavingAccount extends Account{
    interrestRate
}

Class Stock  {
    ticker
    quantity
}

Class StockOrder{
    commission
}

Customer "1" -- "1..*" Account
InvestmentAccount "*" --> "*" Stock
StockOrder "*" --> "1" Stock


@enduml