@startuml
left to right direction

class Identity{


    - uid
    - displayName
    - email



    + getDisplayedName()
    + getEmail()
    + getUid()
}


class PhoneBook {
	~List<Identity> identityList
	+PhoneBook()
	+List<Identity> display()
	+void inputIdentityInformation(String firstName, String lastName)
}

Identity "*"-- PhoneBook

@enduml