@startuml
left to right direction
class Human{
    + playWithDog()
}

class Dog{
    ..Properties..
    - color
    - size

    ..Methods..
    +run()
    +eat(Food food)
    +bringBackTheBall(Ball ball)

}


Human --> "< returns the ball" Dog :<b>bringBackTheBall(</b> theRedBall <b>)</b>

@enduml