@startuml

A "1"--"*" B
note bottom
A has 0 or more B
B has exactly one A
end note
Class H extends G{
}
note left
H specializes G
(H inherits from G)
end note
C o-- D
note bottom
C has an aggregation of D
end note
E *-- F
note bottom
E is composed of F
end note

@enduml